# Generated by Django 4.0.6 on 2022-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('performer', '0002_alter_performer_description_alter_performer_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('start', models.TimeField(verbose_name='Начало')),
                ('end', models.TimeField(verbose_name='Конец')),
                ('date', models.DateField(verbose_name='Дата проведения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='events/photos', verbose_name='Фото')),
                ('performer', models.ManyToManyField(related_name='events', to='performer.performer')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
