# Generated by Django 4.0.6 on 2022-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название места')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('photo', models.ImageField(upload_to='locations/photos', verbose_name='Фото')),
                ('event', models.ManyToManyField(related_name='locations', to='event.event')),
            ],
            options={
                'verbose_name': 'Место проведения',
                'verbose_name_plural': 'Места проведения',
            },
        ),
    ]
