# Generated by Django 4.0.6 on 2022-07-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
    ]
