# Generated by Django 4.0.6 on 2022-07-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performer',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='performer',
            name='photo',
            field=models.ImageField(upload_to='performers/photos', verbose_name='Фото'),
        ),
    ]
