# Generated by Django 4.0.6 on 2022-07-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performer', '0002_alter_performer_description_alter_performer_photo'),
        ('location', '0002_remove_location_event'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ManyToManyField(related_name='events', to='location.location', verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='performer',
            field=models.ManyToManyField(related_name='events', to='performer.performer', verbose_name='Выступающий'),
        ),
    ]
