# Generated by Django 4.0.6 on 2022-07-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Выступающий')),
                ('description', models.TextField(max_length=255, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='performers', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Выступающий',
                'verbose_name_plural': 'Выступающие',
            },
        ),
    ]
